### ISSUE TITLE
PDF doesn't build "out of the box" on Ubuntu Karmic as at 2010-01-15T10:45+00:00

### ISSUE THREAD

**Issue by russel** [tjweir/liftbook#3]
I cloned the repository.  Running "make master.aux" leads to:

! LaTeX Error: Unknown graphics extension: .eps.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.64 ...ing"images/Traditional Model\string".eps}}
                                                  \subfloat[AJAX Application...

**Comment by dchenbecker** [comment]
Cleaned up and fixed Makefile

This closed by 283da7281eba3ba083ddf985cf4add431ef284c1. The export from LyX to LaTeX was improperly done
as plain latex instead of pdflatex, which is why the "EPS" files
were showing up. I also cleaned up the Makefile to make it a bit
more friendly, as well as automatically rerunning pdflatex so
that all references are updated properly.

**Comment by russel** [comment]
Works for me now.  Thanks.
